config/routes.rb
Rails.application.routes.draw do
  resources :greetings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/greeting.rb
class Greeting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  before_action :set_greeting, only: %i[ show edit update destroy ]

  # GET /greetings or /greetings.json
  def index
    @greetings = Greeting.all
  end

  # GET /greetings/1 or /greetings/1.json
  def show
  end

  # GET /greetings/new
  def new
    @greeting = Greeting.new
  end

  # GET /greetings/1/edit
  def edit
  end

  # POST /greetings or /greetings.json
  def create
    @greeting = Greeting.new(greeting_params)

    respond_to do |format|
      if @greeting.save
        format.html { redirect_to @greeting, notice: "Greeting was successfully created." }
        format.json { render :show, status: :created, location: @greeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /greetings/1 or /greetings/1.json
  def update
    respond_to do |format|
      if @greeting.update(greeting_params)
        format.html { redirect_to @greeting, notice: "Greeting was successfully updated." }
        format.json { render :show, status: :ok, location: @greeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /greetings/1 or /greetings/1.json
  def destroy
    @greeting.destroy!

    respond_to do |format|
      format.html { redirect_to greetings_path, status: :see_other, notice: "Greeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_greeting
      @greeting = Greeting.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def greeting_params
      params.expect(greeting: [ :name, :message ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/views/greetings/_form.html.erb
<%= form_with(model: greeting) do |form| %>
  <% if greeting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(greeting.errors.count, "error") %> prohibited this greeting from being saved:</h2>

      <ul>
        <% greeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.textarea :message %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/greetings/_greeting.html.erb
<div id="<%= dom_id greeting %>">
  <p>
    <strong>Name:</strong>
    <%= greeting.name %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= greeting.message %>
  </p>

</div>

app/views/greetings/edit.html.erb
<% content_for :title, "Editing greeting" %>

<h1>Editing greeting</h1>

<%= render "form", greeting: @greeting %>

<br>

<div>
  <%= link_to "Show this greeting", @greeting %> |
  <%= link_to "Back to greetings", greetings_path %>
</div>

app/views/greetings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Greetings" %>

<h1>あいさつを投稿しよう</h1>
<p>現在のあいさつ数は <%= @greetings.count %> 件です。</p>
<div id="greetings">
  <% @greetings.each do |greeting| %>
    <%= render greeting %>
    <p>
      <%= link_to "表示", greeting %>
    </p>
  <% end %>
</div>

<%= link_to "新規あいさつを作成", new_greeting_path %>

app/views/greetings/new.html.erb
<% content_for :title, "New greeting" %>

<h1>New greeting</h1>

<%= render "form", greeting: @greeting %>

<br>

<div>
  <%= link_to "Back to greetings", greetings_path %>
</div>

app/views/greetings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @greeting %>

<div>
  <%= link_to "Edit this greeting", edit_greeting_path(@greeting) %> |
  <%= link_to "Back to greetings", greetings_path %>

  <%= button_to "Destroy this greeting", @greeting, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Root" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>